# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='login',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
